name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - name: Get current date
      id: date
      run: |
        echo "{date}={$(date +'%Y-%m-%dT%H:%M')}" >> $GITHUB_STATE
    - name: Test with environment variables
      run: echo $TAG_NAME - $RELEASE_NAME
      env:
        TAG_NAME: nightly-tag-${{ env.date }}
        RELEASE_NAME: nightly-release-${{ env.date }}

    - name: Docker Login
      id: docker
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fringe:${{ env.TAG_NAME }}




