name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version from commit
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Docker Login
        id: docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fringe:${{ github.run_number }}

  scan:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Image Scan
        uses: alexandreponte1/dockerimagebuild/.github/workflows/scan.yml@main
        with:
          docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/fringe:${{ github.run_number }}
