name: Trivy Scan

on:
  workflow_call: 
    inputs:
      docker_image:
        required: true
        type: string
        description: "Tag da imagem que deve ser escaneada"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Executar o scan de vulnerabilidade
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ inputs.docker_image }}
          scan-type: image
          format: 'json'
          exit-code: 0
          output: 'resultado-trivy.json'
          severity: UNKNOWN,CRITICAL,HIGH,MEDIUM,LOW


  trivy:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # Docker Hub username
        password: ${{ secrets.DOCKERHUB_TOKEN }}    # Docker Hub access token

    - name: Executar o scan de vulnerabilidade
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: alexandreponte/fringe:20        # Nome e tag da imagem Docker a ser escaneada
        scan-type: image
        format: 'json'
        exit-code: 1
        output: 'resultado-trivy.json'
        severity: CRITICAL,HIGH,MEDIUM,LOW

    - name: Upload Trivy Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-report
        path: resultado-trivy.json


      
      # - name: Upload do arquivo de resultado do trivy
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: trivy
      #     path: resultado-trivy.json














# name: Trivy Scan

# on:
#   workflow_call: 
#     inputs:
#       docker_image:
#         required: true
#         type: string
#         description: "Tag da imagem que deve ser escaneada"

# jobs:
#   scan:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Executar o scan de vulnerabilidade
#         uses: aquasecurity/trivy-action@0.20.0
#         with:
#           image-ref: ${{ inputs.docker_image }}
#           scan-type: image
#           format: 'json'
#           exit-code: 0
#           output: 'resultado-trivy.json'
#           severity: UNKNOWN,CRITICAL,HIGH,MEDIUM,LOW
      
#       # - name: Upload do arquivo de resultado do trivy
#       #   uses: actions/upload-artifact@v4
#       #   with:
#       #     name: trivy
#       #     path: resultado-trivy.json












# # name: Trivi Scan
# # on:
# #     workflow_call: 
# #         inputs:
# #             docker_image:
# #                 required: true
# #                 type: string
# #                 description: "Tag da imagem que deve ser escaneada"
# # jobs:
# #     scan:
# #         runs-on: ubuntu-latest
# #         steps:
# #           - name: Executar o scan de vulnerabilidade
# #             uses: aquasecurity/trivy-action@0.20.0
# #             with:
# #               image-ref: ${{ inputs.docker_image }}
# #               scan-type: image
# #               format: 'json'
# #               exit-code: 0
# #               output: 'resultado-trivy.json'
# #               severity: UNKNOWN,CRITICAL,HIGH,MEDIUM,LOW
          
# #           # - name: Upload do arquivo de resultado do trivy
# #           #   uses: actions/upload-artifact@v4
# #           #   with:
# #           #     name: trivy
# #           #     path: resultado-trivy.json
